name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
    - main
    tags:
    - '*'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "14.0"
    - name: Cache boost
      id: cache-boost
      uses: actions/cache@v2
      with:
        path: usr
        key: ${{ runner.os }}-boost-20220415
    - name: Build boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      run: ./.github/depends/boost.sh -b 64 -t gcc
    - name: Build cargo-llvm-codecov-converter
      run: |
        git clone https://github.com/maboesanman/cargo-llvm-codecov-converter.git
        cd cargo-llvm-codecov-converter
        cargo install cargo-llvm-codecov-converter
    - name: Configure
      env:
        FLAGS:    -DCMAKE_CXX_COMPILER=clang++
        CFLAGS:   -Werror -g -Wall -Wextra
        CXXFLAGS: -Werror -g -Wall -Wextra -fprofile-instr-generate -fcoverage-mapping
        LDFLAGS:  -Werror -g -Wall -Wextra
      run: |
         BOOST_ROOT=/home/runner/work/llvm_cov_codecov/llvm_cov_codecov/usr cmake -S ${{ github.workspace }} -B ${{ runner.temp }} ${FLAGS} -DCMAKE_C_FLAGS="${CFLAGS}" -DCMAKE_CXX_FLAGS="${CXXFLAGS}" -DCMAKE_EXE_LINKER_FLAGS="${LDFLAGS}"
    - name: Compile
      run: |
        VERBOSE=1 cmake --build ${{ runner.temp }} --clean-first
    - name: Test
      working-directory: ${{ runner.temp }}
      run: |
        ctest -VV
    - name: Coverage
      run: |
        pwd
        find -name default.profraw
        #LLVM_PROFILE_FILE="test1.profraw"  ${{ runner.temp }}/test/test1
        llvm-profdata merge -sparse default.profraw -o test1.profdata
        llvm-cov export -instr-profile=test1.profdata test/test1 > coverage.json
        #llvm-cov export -instr-profile=test1.profdata test/test1 | cargo-llvm-codecov-converter > coverage.json
        cat coverage.json
        #curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov && ./codecov
        bash <(curl -s https://codecov.io/bash) -f coverage.json || echo "Codecov did not collect coverage reports"
